#!/bin/bash

read -p "Enter source directory: " source_dir

if [ ! -d "$source_dir" ]; then
    echo "Source directory '$source_dir' does not exist."
    exit 1
fi

mkdir -p backup_dir
backup=backup_dir

Timestamp=$(date "+%Y-%m-%d_%H-%M-%S")
Backup_name="${backup}"_"$Timestamp"

mkdir -p "$Backup_name"

echo "Backup directory created: $Backup_name"
echo "Copying .txt files... "
cp "$source_dir"/*.txt "$Backup_name"/

num_files=$(ls -1 "$Backup_name" 2>/dev/null | wc -l)

echo "Backup complete! Files backed up: $num_files"
