#!/bin/bash

read -p "Enter filename to check: " filename

if [ -f "$filename" ]; then
  echo "'$filename' exists"
  if [ -r "$filename" ];then
    echo "'$filename' is readable"
  else
    echo "'$filename' is not readable"
  fi
  
  if [ -w "$filename" ]; then
    echo "'$filename' is writable"
  else
    echo "'$filename' is not writable"
  fi
  
  if [ -x "$filename" ]; then
    echo "'$filename' is executable"
  else
    echo "'$filename' is not executable"
  fi

else
  echo "'$filename' does not exist"
  exit 1
fi
